[helpers]

[default]
depends = []

[default.files]
"bottom.toml" = "~/.config/bottom/bottom.toml"

"fish.fish" = "~/.config/fish/config.fish"
"fish-oh-my-posh.fish" = "~/.config/fish/oh-my-posh.fish"
"M365Princess.omp.json" = { target = "~/.poshthemes/M365Princess.omp.json", type = "symbolic" }

gitconfig = "~/.gitconfig"
gitignore = "~/.gitignore"

"helix-lang.toml" = "~/.config/helix/languages.toml"
"helix.toml" = "~/.config/helix/config.toml"

"rustfmt.toml" = "~/rustfmt.toml"

"zellij.kdl" = "~/.config/zellij/config.kdl"

[default.variables]

[settings]
default_target_type = "automatic"
